demo2app/urls.py
from django.urls import path, include

from . import views
app_name='demo2app'

urlpatterns = [

    path('',views.index,name='index'),
    path('movies/<int:movie_id>/',views.details,name='details'),
    path('add/',views.add_movie,name='add_movie'),
    path('update/<int:id>/',views.update,name='update'),
    path('delete/<int:id>/',views.delete,name='delete')
]

demo2project/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('demo2app.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

demo2app/models.py
from django.db import models

# Create your models here.
class movie(models.Model):
    name=models.CharField(max_length=250)
    desc=models.TextField()
    year=models.IntegerField()
    img=models.ImageField(upload_to='images')

    def __str__(self):
        return self.name

demo2app/forms.py
from django import forms
from .models import movie

class MovieForm(forms.ModelForm):
    class Meta:
        model=movie
        fields=['name','desc','year','img']

demo2app/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .models import movie
from .forms import MovieForm

# Create your views here.
def index(request):
    result=movie.objects.all()


    return render(request,'index.html',{'show':result})
def details(request,movie_id):
    mov=movie.objects.get(id=movie_id)
    return render(request,"details.html",{'mov':mov})
def add_movie(request):
    if request.method=='POST':
        name=request.POST.get('name',)
        desc=request.POST.get('desc',)
        year=request.POST.get('year',)
        img=request.FILES['img']
        mov=movie(name=name,desc=desc,year=year,img=img)
        mov.save()
    return render(request,'add.html')
def update(request,id):
    mov=movie.objects.get(id=id)
    frm=MovieForm(request.POST or None,request.FILES,instance=mov)
    if frm.is_valid():
        frm.save()
        return redirect('/')
    return render(request,'update.html',{'form':frm,'mov':mov})
def delete(request,id):
    mov=movie.objects.get(id=id)
    if request.method=='POST':
        mov.delete()
        return redirect('/')
    return render(request,'delete.html')

templates/add.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <input type="text" name="name" placeholder="enter movie name">
  <input type="text" name="desc" placeholder="about the movie">
  <input type="text" name="year" placeholder="year of the movie">
  <input type="file" name="img">
  <input type="submit">


</form>

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>result</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'style.css' %}">
</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark">
  <a class="navbar-brand" href="#">
    ONLINE MOVIE STORE
  </a>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/delete.html
<form method="post">
    {% csrf_token %}
    Are you sure?
    <input type="submit">
</form>

templates/details.html
{% extends 'base.html' %}
{% block body %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <image src= "{{mov.img.url}}" width="300" height="400";></image>
        </div>
        <div class="col-md-6">
        <h2>{{mov.name}}</h2>
        <h5>{{mov.desc}}</h5>
        <h5>{{mov.year}}</h5>
            <div class="row">
    <p><a href="{% url 'demo2app:update' mov.id %}" class="btn btn-warning">update</a></p>&nbsp;
    <p><a href="{% url 'demo2app:delete' mov.id %}" class="btn btn-danger">Delete</a></p>
            </div>
</div>
 </div>
</div>

</body>
</html>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% block body %}
<div class="container">
    <div class="row">
        {% for i in show %}
        <div class="col-md-4">
        <div class="card" style="width: 18rem;">
  <img class="card-img-top" src="{{i.img.url}}" alt="Card image cap" height="290px;">
  <div class="card-body">
    <h5 class="card-title">{{i.name}}</h5>
    <a href="{% url 'demo2app:details' i.id %}" class="btn btn-primary">view details</a>
  </div>
</div>
            </div>
        {% endfor %}
    </div>
</div>



{% endblock %}

templates/update.html
<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  {{form.as_p}}
  <input type="submit">
</form>